version: '3'


services:
  web:
    build: .
    restart: always
    environment:
      APP_MONGO_USER: ${APP_MONGO_USER}
      APP_MONGO_PASS: ${APP_MONGO_PASS}
    ports: 
      - "8080:3000"
    links: 
      - mongo
    depends_on: 
      - mongo-express

  mongo:
    build: images/mongo
    restart: always
    environment:
       MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
       APP_MONGO_HOST: ${MONGO_HOST}
       MONGO_PORT: ${MONGO_PORT}
       MONGO_ROOT_USER: ${MONGO_ROOT_USERNAME}
       MONGO_ROOT_PASS: ${MONGO_ROOT_PASSWORD}
       APP_MONGO_USER: ${APP_MONGO_USER}
       APP_MONGO_PASS: ${APP_MONGO_PASS}
       APP_MONGO_DB: ${APP_MONGO_DB}
       APP_DEFAULT_USER: ${APP_DEFAULT_USER}
       APP_DEFAULT_PASS: ${APP_MONGO_PASS}
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
    depends_on: 
      - mongo


volumes:
  mongo-data:

