version: '3'


services:
  web:
    build: .
    restart: always
    environment:
      APP_MONGO_USER: ${APP_MONGO_USER}
      APP_MONGO_PASS: ${APP_MONGO_PASS}
    ports: 
      - "8080:3000"
    links: 
      - mongo
    depends_on: 
      - mongo-express

  mongo:
    build: images/mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
    depends_on: 
      - mongo


volumes:
  mongo-data:

