version: "3.7"

services:
  paddle-planner-api: # Node.js App
    container_name: paddle-planner-api
    build: ../app
    ports:
     - "3000:${API_PORT:-3000}" # Expose API port
     - "9229:9229" # Expose Node process debug port (disable in production)
    environment: # Set ENV vars
     - LOG_DIR=${LOG_DIR:-/tmp}
     - BUOY_LOG_FILE=${BUOY_LOG_FILE:-log.log}
     - JSON_LOG_FILE=${JSON_LOG_FILE:-json-log.log}
     - NODE_ENV=local
     - ES_HOST=elasticsearch
     - ES_PORT=9200
     - PORT=3000
     - LOG_DATA=${LOG_DATA:-false}
     - AUTO_BUOY_DATA_ENABLED:${AUTO_BUOY_DATA_ENABLED:-false}
    volumes: # Persist ES data in seperate "esdata" volume
     - paddle-planner-app-data:/logs/
    links: 
     - elasticsearch
    depends_on:
     - elasticsearch
    restart: on-failure


  elasticsearch: # Elasticsearch Instance
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    volumes: # Persist ES data in seperate "esdata" volume
     - esdata:/usr/share/elasticsearch/data
    environment:
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - discovery.type=single-node
    ports: # Expose Elasticsearch ports
     - "9300:9300"
     - "9200:9200"
    expose:
     - 9300
     - 9200


  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - "5601:5601"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8081:80
    volumes:
      - ${PWD}/config/nginx-config/:/etc/nginx/conf.d/
    command: /bin/bash -c "nginx -g 'daemon off;'"
    ulimits:
      nproc: 65535
    restart: on-failure
      

  filebeat: 
    container_name: filebeat
    image:  docker.elastic.co/beats/filebeat:7.1.1
    volumes:
     - "${PWD}/config/filebeat/filebeat.json.yml:/usr/share/filebeat/filebeat.yml"
     - /var/lib/docker/containers:/var/lib/docker/containers:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - paddle-planner-app-data:/logs/
    environment:
     - output.elasticsearch.hosts:elasticsearch:9200"
     - LOG_DIR=${LOG_DIR:-/tmp}
     - BUOY_LOG_FILE=${BUOY_LOG_FILE:-log.log}
     - JSON_LOG_FILE=${JSON_LOG_FILE:-json-log.log}
    links:
      - elasticsearch



    
volumes: # Define seperate volume for Elasticsearch data
  esdata:
  paddle-planner-app-data:
