service: paddle-planner
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: "us-west-2"
  vpc:
    subnetIds:
        - ${env:SUBNET_ID}

functions:
  weather:
    handler: handler.endpoint
    events:
      - http:
          path: echo
          method: get
