service: paddle-planner
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: "us-west-2"
  stage: "dev"
  vpc:
    subnetIds:
        - ${env:SUBNET_ID}

functions:
  geo_latlon:
    handler: api/geo.latlong
    memorySize: 128
    description: Get Location details via lat long
    events:
      - http:
          path: geo/{lat}/{long}
          method: get
          cors: true
  geo_city:
    handler: api/geo.city
    memorySize: 128
    description: Get Location details via City name, eg. Galway
    events:
      - http:
          path: geo/{city}
          method: get
          cors: true
              


