- name: paddle-planner
  type: group
  description: >
    Contains fields for the paddle-planner Buoy logs. 
  fields:    
    - name: buoy_report.windGust
      type: integer
      ignore_malformed: true 
      



