filebeat.config:
  modules:
    path:  /usr/share/filebeat/modules.d/*.yml
    reload.enabled: true

filebeat.modules:    
  - module: elasticsearch
    server:
     enabled: true
 
setup.kibana:
  host: "kibana:5601"    

setup.ilm:
  enabled: false
  rollover_alias: "paddle-planner-"
  pattern: "{now/d}-000001"
  overwrite: true

setup.template:
  name: "paddle-planner"
  pattern: "paddle-planner-*"
  enabled: true
  overwrite: true
  fields: "/usr/share/filebeat/fields.yml"
 

filebeat.inputs:
  - type: log
    enabled: true
    paths:   
      - ${LOG_DIR}/${BUOY_LOG_FILE}
    json.keys_under_root: true
    json.add_error_key: true

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  index: "paddle-planner-%{[agent.version]}-%{+yyyy.MM.dd}"
  console:
    pretty: true



logging.level: debug
logging.selectors: "*"



