filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

setup.kibana:
  host: "kibana:5601"    

filebeat.inputs:

- type: log
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log
  paths:
    - ${LOG_DIR}/${JSON_LOG_FILE}

- type: log      
  # Identifies the last two columns as the end of an entry and then prepends the previous lines to it
  multiline.pattern: ',\d+,[^\",]+$'
  multiline.negate: true
  multiline.match: before
  paths:   
    - ${LOG_DIR}/${BUOY_LOG_FILE}

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
