filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

filebeat.modules:    
  - module: elasticsearch
    server:
     enabled: true

setup.kibana:
  host: "kibana:5601"    

setup.ilm:
  enabled: false
  rollover_alias: "paddle-planner-"
  pattern: "{now/d}-000001"
  overwrite: true

setup.template:
  name: "paddle-planner"
  pattern: "paddle-planner-*"
  enabled: true
  overwrite: true
  fields: "/usr/share/filebeat/fields.yml"


filebeat.inputs:
  - type: log
    enabled: true
    paths:   
      - ${LOG_DIR}/${BUOY_LOG_FILE}
    json.keys_under_root: false
    tags: ['buoy']
    processors:
    - decode_json_fields:
        fields: ["message"]
    - convert:
        fields:
           - {from: "json.message.reportDate", to: "report_date", mode: "copy"}
           - {from: "json.message.reportTime", to: "report_time", mode: "copy"}
        ignore_missing: false
        fail_on_error: false
    - script:
        lang: javascript
        id: my_filter_buoy
        source: >
          function process(event) {
            var timearray  = event.Get("report_date").split("-", 3);
            var elasticTime = timearray[2] +"-"+ timearray[1] +"-"+ timearray[0];
            var reportHour = event.Get("report_time");
            if(reportHour.charAt(0) == ' ')
              reportHour="0"+reportHour.trim();
            event.Put("report_date", elasticTime + "T" + reportHour + ":00");
            event.Tag("time-modified");
          }
  - type: log
    enabled: true
    paths:   
      - ${LOG_DIR}/${WEATHER_LOG_FILE}
    json.keys_under_root: false
    tags: ['weather-forecast']
    processors:
    - decode_json_fields:
        fields: ["message"]
    - script:
        lang: javascript
        id: my_filter_weather
        source: >
          function process(e){
            var _date  = e.Get("json.message.dt_txt").split(" ",2)
            e.Put("report_date", _date[0]+'T'+_date[1])
            e.Tag("time-modified");
          }
        
          
output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  index: "paddle-planner-%{[agent.version]}-%{+yyyy.MM.dd}"
  console:
    pretty: true

logging.level: debug
logging.selectors: "*"

