filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

setup.kibana:
  host: "kibana:5601"    

filebeat.inputs:

- type: log
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log
  paths:
    - /tmp/paddle-planner-json.log

- type: log      
  paths:   
    - /tmp/paddle-planner-buoys.log

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
