filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

filebeat.modules:    
  - module: elasticsearch
    server:
     enabled: true

setup.kibana:
  host: "kibana:5601"    

setup.ilm:
  enabled: false
  rollover_alias: "paddle-planner-"
  pattern: "{now/d}-000001"
  overwrite: true

setup.template:
  name: "paddle-planner"
  pattern: "paddle-planner-*"
  enabled: true
  overwrite: true
  #  fields: "/usr/share/filebeat/fields.yml"


filebeat.inputs:
  - type: log
    enabled: true
    paths:   
      - ${LOG_DIR}/${BUOY_LOG_FILE}
    json.keys_under_root: false

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
  - convert:
      fields:
        - {from: "json.message.windGust", to: "windGust", type: "integer"}
        - {from: "json.message.period", to: "period", type: "double"}
        - {from: "json.message.created_at", to: "created_at"}
        - {from: "json.message.dewPoint", to: "dewPoint", type: "double"}
        - {from: "json.message.height", to: "height", type: "double"}
        - {from: "json.message.humiidty", to: "humiidty", type: "integer"}
        - {from: "json.message.ID", to: "ID"}
        - {from: "json.message.name", to: "name"}
        - {from: "json.message.pressure", to: "pressure", type: "double"}
        - {from: "json.message.reportDate", to: "reportDate", type: "double"}
        - {from: "json.message.seaTemp", to: "seaTemp", type: "double"}
        - {from: "json.message.temp", to: "temp", type: "double"}
        - {from: "json.message.time", to: "time"}
        - {from: "json.message.upadted_at", to: "upadted_at"}
        - {from: "json.message.windDir", to: "windDir", type: "double"}
        - {from: "json.message.windGust.", to: "windGust", type: "double"}
        - {from: "json.message.windSpeed", to: "windSpeed", type: "double"}
        - {from: "json.message.wmoID", to: "wmoID"}
      ignore_missing: false
      fail_on_error: false

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  index: "paddle-planner-%{[agent.version]}-%{+yyyy.MM.dd}"
  console:
    pretty: true

logging.level: debug
logging.selectors: "*"

